# Generated by Django 5.0.7 on 2024-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieTitle', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('reviewContent', models.TextField(max_length=200)),
                ('rating', models.TextField(choices=[('1-Star', '1-Star'), ('2-Star', '2-Star'), ('3-Star', '3-Star'), ('4-Star', '4-Star'), ('5-Star', '5-Star')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_email_id', models.EmailField(max_length=100)),
                ('status', models.TextField(choices=[('Published', 'Published'), ('Not Published', 'Not Published')])),
                ('genres', models.TextField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Sci-Fi', 'Sci-Fi'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller')])),
            ],
        ),
    ]
